<!DOCTYPE html>
<html>
	<head>
		<title>Holiday API</title>
	</head>
	<body>
		<?php require $this->template; ?>
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-46049009-1', 'holidayapi.com');
		  ga('send', 'pageview');
		</script>
		<?php
		$honey_pots = [
			'<a href="http://holidayapi.com/iratedungeon.php"><!-- chap-capability --></a>',
			'<a href="http://holidayapi.com/iratedungeon.php"><img src="chap-capability.gif" height="1" width="1" border="0"></a>',
			'<a href="http://holidayapi.com/iratedungeon.php" style="display: none;">chap-capability</a>',
			'<div style="display: none;"><a href="http://holidayapi.com/iratedungeon.php">chap-capability</a></div>',
			'<a href="http://holidayapi.com/iratedungeon.php"></a>',
			'<!-- <a href="http://holidayapi.com/iratedungeon.php">chap-capability</a> -->',
			'<div style="position: absolute; top: -250px; left: -250px;"><a href="http://holidayapi.com/iratedungeon.php">chap-capability</a></div>',
			'<a href="http://holidayapi.com/iratedungeon.php"><span style="display: none;">chap-capability</span></a>',
			'<a href="http://holidayapi.com/iratedungeon.php"><div style="height: 0px; width: 0px;"></div></a>',
		];

		shuffle($honey_pots);

		echo current($honey_pots);
		?>
	</body>
</html>
