<!DOCTYPE html>
<html>
	<head>
		<title>Holiday API</title>
		<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="<?=$__dynamic->css('/css/core.less');?>">
		<meta name="viewport" content="width=device-width, user-scalable=no">
		<script src="//load.sumome.com/" data-sumo-site-id="54926a714a38c69d4b5402706a836ffaab038eea6a977d2445eee4623d9712c9" async></script>
	</head>
	<body>
		<div class="container">
			<div class="col-xs-12 col-sm-6 col-sm-offset-3">
				<header>
					<h1>Holiday API</h1>
					<img class="logo" src="/img/logo.png">
				</header>
				<?php require $this->template; ?>
				<footer class="lead">
					Built with <span class="heart">&hearts;</span> in <a href="http://builtwithlove.in/gravityblvd" target="_blank">Tampa, FL</a>
				</footer>
			</div>
		</div>
		<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/js/bootstrap.min.js"></script>
		<script>
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

			ga('create', 'UA-46049009-1', 'holidayapi.com');
			ga('send', 'pageview');
		</script>
	</body>
</html>
