<!DOCTYPE html>
<html>
	<head>
		<title>Holiday API</title>
	</head>
	<body>
		<?php require $this->template; ?>
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-46049009-1', 'holidayapi.com');
		  ga('send', 'pageview');
		</script>
		<!-- AddThis Button BEGIN -->
		<div class="addthis_toolbox addthis_default_style">
		<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
		<a class="addthis_button_tweet"></a>
		<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
		<a class="addthis_button_linkedin_counter"></a>
		<a class="addthis_counter addthis_pill_style"></a>
		</div>
		<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
		<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-529535354cd72841"></script>
		<!-- AddThis Button END -->
		<?php
		$honey_pots = array(
			'<a href="http://holidayapi.com/iratedungeon.php"><!-- chap-capability --></a>',
			'<a href="http://holidayapi.com/iratedungeon.php"><img src="chap-capability.gif" height="1" width="1" border="0"></a>',
			'<a href="http://holidayapi.com/iratedungeon.php" style="display: none;">chap-capability</a>',
			'<div style="display: none;"><a href="http://holidayapi.com/iratedungeon.php">chap-capability</a></div>',
			'<a href="http://holidayapi.com/iratedungeon.php"></a>',
			'<!-- <a href="http://holidayapi.com/iratedungeon.php">chap-capability</a> -->',
			'<div style="position: absolute; top: -250px; left: -250px;"><a href="http://holidayapi.com/iratedungeon.php">chap-capability</a></div>',
			'<a href="http://holidayapi.com/iratedungeon.php"><span style="display: none;">chap-capability</span></a>',
			'<a href="http://holidayapi.com/iratedungeon.php"><div style="height: 0px; width: 0px;"></div></a>',
		);

		shuffle($honey_pots);

		echo current($honey_pots);
		?>
	</body>
</html>
