<h1>Holiday API</h1>

<p>The goal of this project is to provide a comprehensive &amp; free API for obtaining information about holidays.</p>

<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style">
<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
<a class="addthis_button_tweet"></a>
<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
<a class="addthis_button_linkedin_counter"></a>
<a class="addthis_counter addthis_pill_style"></a>
</div>
<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-529535354cd72841"></script>
<!-- AddThis Button END -->

<h2>Usage</h2>

<p>To retrieve a list of holidays, simply make a GET request to <a href="http://holidayapi.com/v1/holidays" target="_blank">http://holidayapi.com/v1/holidays</a></p>

<h3>Parameters</h3>

<ul>
	<li><code>country</code> - required, <a href="http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2" target="_blank">ISO 3166-1 alpha-1</a> format. Valid codes: BE, US</li>
	<li><code>year</code> - required, 4 digits</li>
	<li><code>month</code> - optional</li>
	<li><code>day</code> - optional</li>
</ul>

<h3>Status Codes</h3>

<ul>
	<li><strong>200</strong>: No one goof’d</li>
	<li><strong>400</strong>: You dun goof’d</li>
	<li><strong>500</strong>: We dun goof’d</li>
</ul>

<h3>Response</h3>

<pre>{"status":200,"holidays":[{"name":"Star Wars Day","country":"US","date":"2013-05-04"}]}</pre>

<h2>Want to help?</h2>

<p>If you are interested in contributing to this API either with design, development or helping with your country’s holiday list (each country is a JSON file), <a href="https://github.com/joshtronic/holidayapi.com" target="_blank">go fork this API over on Github</a>. If you have any suggestions or find a bug, <a href="https://github.com/joshtronic/holidayapi.com/issues">please take the time to report it</a>. If you like what I’ve created and find it to be useful, please consider tipping:</p>

<p><script data-gittip-username="joshtronic" src="//gttp.co/v1.js"></script></p>

<h2>Contributors</h2>

<p>The Holiday API was created by <a href="https://github.com/joshtronic">Josh Sherman</a> and is provided as a free service. Special thanks to <a href="https://github.com/LGnap">LGnap</a> for providing a holiday list for Belgium.</p>
