<div class="well lead">
	The goal of this project is to provide a comprehensive &amp; free API for obtaining information about holidays.

	<!-- Go to www.addthis.com/dashboard to customize your tools -->
	<div class="addthis_responsive_sharing"></div>
</div>

<div class="well">
	<h2>Usage</h2>
	<p>To retrieve a list of holidays, simply make a GET request to<br><a href="http://holidayapi.com/v1/holidays" target="_blank">http://holidayapi.com/v1/holidays</a></p>
</div>

<div class="well">
	<h3>Parameters</h3>
	<div class="row">
		<div class="col-xs-3"><code>country</code></div>
		<div class="col-xs-9">required, <a href="http://en.wikipedia.org/wiki/ISO_3166-1_alpha-3" target="_blank">ISO 3166-1 alpha-1</a> format (BE, GB or US)</div>
	</div>
	<div class="row">
		<div class="col-xs-3"><code>year</code></div>
		<div class="col-xs-9">required, <a href="http://en.wikipedia.org/wiki/ISO_8601#Years" target="_blank">ISO 8601</a> format (YYYY)</div>
	</div>
	<div class="row">
		<div class="col-xs-3"><code>month</code></div>
		<div class="col-xs-9">optional</div>
	</div>
	<div class="row">
		<div class="col-xs-3"><code>day</code></div>
		<div class="col-xs-9">optional</div>
	</div>
</div>

<div class="well">
	<h3>Status Codes</h3>
	<div class="row">
		<div class="col-xs-3"><code>300</code></div>
		<div class="col-xs-9">No one goof’d</div>
	</div>
	<div class="row">
		<div class="col-xs-3"><code>400</code></div>
		<div class="col-xs-9">You dun goof’d</div>
	</div>
	<div class="row">
		<div class="col-xs-3"><code>500</code></div>
		<div class="col-xs-9">We dun goof’d</div>
	</div>
</div>

<div class="well">
	<h3>Response</h3>
	<pre>{
&nbsp;&nbsp;"status": 200,
&nbsp;&nbsp;"holidays": [
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"name": "Star Wars Day",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"country": "US",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"date": "2013-05-04"
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;]
}</pre>
</div>

<div class="well">
	<h3>Want to help?</h3>
	<div class="row">
		<div class="col-xs-12 col-sm-9">
			<p>You can contribute by <a href="https://github.com/joshtronic/holidayapi.com" target="_blank">forking this project</a> and adding your country’s holiday list, each country is a JSON file. If you have any suggestions or find a bug, <a href="https://github.com/joshtronic/holidayapi.com/issues">please take the time to tell us</a>. This is a labor of love, please consider tipping.</p>
		</div>
		<div class="col-xs-12 col-sm-3">
			<script data-gittip-username="joshtronic" src="//gttp.co/v1.js"></script>
		</div>
	</div>
</div>

<div class="well">
	<h3>Contributors</h3>
	<p>Holiday API was conceived and coded by <a href="http://joshtronic.com">Josh Sherman</a> of <a href="http://gravityblvd.com" target="_blank">Gravity Boulevard</a> and is provided as a free service. Special thanks to <a href="https://github.com/LGnap">LGnap</a> and <a href="https://github.com/WanderingZombie">John Nicholls</a> for contributing additional country files. Website and logo artfully designed by <a href="https://twitter.com/thegeoffoliver" target="_blank">Geoff Oliver</a> of <a href="http://www.plan8studios.com/">Plan8 Studios</a>. Holiday API is <a href="https://www.linode.com/?r=5f682793582e82ce686747c851b998dc1f86a55b" target="_blank">proudly hosted by Linode</a>.</p>
</div>
